M48
; DRILL file {KiCad 8.0.0-rc2-494-g6bc7bcffef} date 2024-02-15T01:57:23+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-02-15T01:57:23+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0-rc2-494-g6bc7bcffef
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X124.61Y-98.145
X130.39Y-98.145
M30
